# Generated by Django 4.2.13 on 2026-05-12 22:20

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SessionSummaryMetric",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("total_participants", models.PositiveIntegerField(default=0)),
                ("peak_concurrent", models.PositiveIntegerField(default=0)),
                ("total_chat_messages", models.PositiveIntegerField(default=0)),
                ("total_quizzes", models.PositiveIntegerField(default=0)),
                ("avg_quiz_accuracy", models.FloatField(default=0.0)),
                ("total_points_awarded", models.PositiveIntegerField(default=0)),
                ("top_emojis", models.JSONField(default=list)),
                ("points_distribution", models.JSONField(default=dict)),
            ],
            options={
                "verbose_name": "Métricas de sesión",
            },
        ),
        migrations.CreateModel(
            name="StageMetric",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("time_spent_seconds", models.PositiveIntegerField(default=0)),
                ("estimated_seconds", models.PositiveIntegerField(default=0)),
                ("participants_online", models.PositiveIntegerField(default=0)),
                ("quiz_response_rate", models.FloatField(default=0.0)),
                ("quiz_accuracy_rate", models.FloatField(default=0.0)),
                ("emoji_counts", models.JSONField(default=dict)),
                ("total_chat_messages", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name": "Métrica de etapa",
                "ordering": ["created_at"],
            },
        ),
    ]
