# Generated by Django 4.2.13 on 2026-05-12 22:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("live_sessions", "0001_initial"),
        ("analytics", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="stagemetric",
            name="session",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="stage_metrics",
                to="live_sessions.livesession",
            ),
        ),
        migrations.AddField(
            model_name="stagemetric",
            name="stage",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="metrics",
                to="live_sessions.stage",
            ),
        ),
        migrations.AddField(
            model_name="sessionsummarymetric",
            name="session",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="summary_metric",
                to="live_sessions.livesession",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="stagemetric",
            unique_together={("session", "stage")},
        ),
    ]
