"""
Gamification app — Models
RF-GAME-01: Spinner (ruleta)
RF-GAME-02: Points & leaderboard
RF-GAME-03: Emoji reactions
RF-GAME-04: Timers
RF-GAME-05: Quiz/Poll
"""
from django.db import models
from django.conf import settings
from core.models import BaseModel


# ── Quiz ──────────────────────────────────────────────────────────────────────

class Quiz(BaseModel):
    """
    Saved quiz template. Owned by an instructor/admin.
    """
    owner = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        related_name="quizzes",
        limit_choices_to={"role__in": ["INSTRUCTOR", "ADMIN"]},
    )
    title = models.CharField(max_length=255)
    description = models.TextField(blank=True)

    class Meta:
        verbose_name = "Quiz guardado"
        verbose_name_plural = "Quizzes guardados"
        ordering = ["-created_at"]

    def __str__(self):
        return self.title


class QuizQuestion(BaseModel):
    """
    Quiz question generated by AI or created manually.
    RF-GAME-05, RF-AI-01
    """

    class QuestionType(models.TextChoices):
        MULTIPLE_CHOICE = "MULTIPLE_CHOICE", "Opción múltiple"
        OPEN = "OPEN", "Respuesta abierta"

    class Difficulty(models.TextChoices):
        EASY = "EASY", "Fácil"
        MEDIUM = "MEDIUM", "Medio"
        HARD = "HARD", "Difícil"

    quiz = models.ForeignKey(
        Quiz,
        on_delete=models.CASCADE,
        null=True,
        blank=True,
        related_name="questions",
    )
    session = models.ForeignKey(
        "live_sessions.LiveSession",
        on_delete=models.CASCADE,
        related_name="quiz_questions",
        null=True,
        blank=True,
    )
    stage = models.ForeignKey(
        "live_sessions.Stage",
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name="quiz_questions",
    )
    text = models.TextField()
    question_type = models.CharField(
        max_length=20,
        choices=QuestionType.choices,
        default=QuestionType.MULTIPLE_CHOICE,
    )
    # For MULTIPLE_CHOICE: list of {"text": "...", "is_correct": bool}
    options = models.JSONField(default=list)
    correct_answer = models.CharField(max_length=1000, blank=True)
    explanation = models.TextField(blank=True)
    difficulty = models.CharField(
        max_length=10, choices=Difficulty.choices, default=Difficulty.MEDIUM
    )
    duration_seconds = models.PositiveIntegerField(default=30)
    # State
    is_launched = models.BooleanField(default=False)
    launched_at = models.DateTimeField(null=True, blank=True)
    closed_at = models.DateTimeField(null=True, blank=True)
    # AI metadata
    generated_by_ai = models.BooleanField(default=False)
    ai_model_used = models.CharField(max_length=100, blank=True)

    class Meta:
        verbose_name = "Pregunta de quiz"
        verbose_name_plural = "Preguntas de quiz"
        ordering = ["created_at"]

    def __str__(self):
        return f"[{self.question_type}] {self.text[:80]}"


class QuizResponse(BaseModel):
    """Student response to a quiz question. RF-GAME-05."""

    question = models.ForeignKey(
        QuizQuestion,
        on_delete=models.CASCADE,
        related_name="responses",
    )
    participant = models.ForeignKey(
        "live_sessions.Participant",
        on_delete=models.CASCADE,
        related_name="quiz_responses",
    )
    answer = models.CharField(max_length=1000)
    is_correct = models.BooleanField(null=True, blank=True)
    answered_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name = "Respuesta de quiz"
        unique_together = [("question", "participant")]

    def __str__(self):
        return f"{self.participant.display_name} → {self.question.text[:40]}"


# ── Points ────────────────────────────────────────────────────────────────────

class PointEvent(BaseModel):
    """
    Immutable record of a point award event. RF-GAME-02.
    Participant.points is the computed total.
    """

    session = models.ForeignKey(
        "live_sessions.LiveSession",
        on_delete=models.CASCADE,
        related_name="point_events",
    )
    participant = models.ForeignKey(
        "live_sessions.Participant",
        on_delete=models.CASCADE,
        related_name="point_events",
    )
    points = models.IntegerField()  # Can be negative (penalty)
    action_label = models.CharField(max_length=200, default="Participación")
    awarded_by = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.SET_NULL,
        null=True,
        related_name="awarded_points",
    )

    class Meta:
        verbose_name = "Evento de puntos"
        verbose_name_plural = "Eventos de puntos"
        ordering = ["-created_at"]


# ── Timer ─────────────────────────────────────────────────────────────────────

class Timer(BaseModel):
    """
    Synchronized countdown timer. RF-GAME-04.
    end_timestamp_utc is what gets broadcast to clients.
    """

    class TimerState(models.TextChoices):
        RUNNING = "RUNNING", "Corriendo"
        PAUSED = "PAUSED", "Pausado"
        CANCELLED = "CANCELLED", "Cancelado"
        FINISHED = "FINISHED", "Finalizado"

    session = models.ForeignKey(
        "live_sessions.LiveSession",
        on_delete=models.CASCADE,
        related_name="timers",
    )
    label = models.CharField(max_length=200, default="Temporizador")
    duration_seconds = models.PositiveIntegerField()
    end_timestamp_utc = models.DateTimeField()
    state = models.CharField(
        max_length=20,
        choices=TimerState.choices,
        default=TimerState.RUNNING,
    )
    paused_at = models.DateTimeField(null=True, blank=True)
    remaining_seconds = models.PositiveIntegerField(null=True, blank=True)

    class Meta:
        verbose_name = "Temporizador"
        ordering = ["-created_at"]
