# Generated by Django 4.2.13 on 2026-05-12 22:20

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("live_sessions", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BoardSnapshot",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("elements", models.JSONField(default=list)),
                ("app_state", models.JSONField(default=dict)),
                ("s3_key", models.CharField(blank=True, max_length=500)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="board_snapshots",
                        to="live_sessions.livesession",
                    ),
                ),
                (
                    "stage",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="board_snapshots",
                        to="live_sessions.stage",
                    ),
                ),
            ],
            options={
                "verbose_name": "Snapshot de pizarra",
                "verbose_name_plural": "Snapshots de pizarra",
                "ordering": ["created_at"],
                "unique_together": {("session", "stage")},
            },
        ),
        migrations.CreateModel(
            name="BoardCollaborator",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("cursor_color", models.CharField(default="#FF5733", max_length=7)),
                ("is_active", models.BooleanField(default=True)),
                ("granted_at", models.DateTimeField(auto_now_add=True)),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                (
                    "participant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="board_permissions",
                        to="live_sessions.participant",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="board_collaborators",
                        to="live_sessions.livesession",
                    ),
                ),
            ],
            options={
                "verbose_name": "Colaborador de pizarra",
                "unique_together": {("session", "participant")},
            },
        ),
    ]
