# Generated by Django 4.2.13 on 2026-05-12 22:20

import apps.live_sessions.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ClassTemplate",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("is_public", models.BooleanField(default=False)),
                ("estimated_duration_minutes", models.PositiveIntegerField(default=60)),
                ("tags", models.JSONField(blank=True, default=list)),
                (
                    "thumbnail",
                    models.ImageField(
                        blank=True, null=True, upload_to="templates/thumbnails/"
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        limit_choices_to={"role__in": ["INSTRUCTOR", "ADMIN"]},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="templates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Plantilla de clase",
                "verbose_name_plural": "Plantillas de clase",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Stage",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                (
                    "stage_type",
                    models.CharField(
                        choices=[
                            ("BOARD", "Pizarra"),
                            ("PDF", "PDF"),
                            ("VIDEO", "Video"),
                            ("QUIZ", "Quiz / Encuesta"),
                            ("CHAT_FOCUS", "Chat enfocado"),
                            ("GAME", "Juego (Ruleta / Timer)"),
                            ("RESOURCE", "Nube de recursos"),
                            ("BREAK", "Descanso"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                ("duration_estimated_minutes", models.PositiveIntegerField(default=10)),
                ("config", models.JSONField(blank=True, default=dict)),
                ("initial_board_state", models.JSONField(blank=True, null=True)),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stages",
                        to="live_sessions.classtemplate",
                    ),
                ),
            ],
            options={
                "verbose_name": "Etapa",
                "verbose_name_plural": "Etapas",
                "ordering": ["order"],
                "unique_together": {("template", "order")},
            },
        ),
        migrations.CreateModel(
            name="LiveSession",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                (
                    "join_code",
                    models.CharField(
                        db_index=True,
                        default=apps.live_sessions.models._generate_join_code,
                        max_length=6,
                        unique=True,
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("SCHEDULED", "Programada"),
                            ("LIVE", "En vivo"),
                            ("PAUSED", "Pausada"),
                            ("ENDED", "Finalizada"),
                        ],
                        db_index=True,
                        default="SCHEDULED",
                        max_length=20,
                    ),
                ),
                ("is_dry_run", models.BooleanField(default=False)),
                ("scheduled_at", models.DateTimeField(blank=True, null=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("paused_at", models.DateTimeField(blank=True, null=True)),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
                ("ai_summary", models.TextField(blank=True)),
                ("is_replay_public", models.BooleanField(default=False)),
                (
                    "current_stage",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="live_sessions.stage",
                    ),
                ),
                (
                    "instructor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="instructed_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="live_sessions",
                        to="live_sessions.classtemplate",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sesión en vivo",
                "verbose_name_plural": "Sesiones en vivo",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Participant",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_guest", models.BooleanField(default=False)),
                ("display_name", models.CharField(max_length=150)),
                ("points", models.IntegerField(default=0)),
                ("can_draw", models.BooleanField(default=False)),
                (
                    "connection_status",
                    models.CharField(
                        choices=[
                            ("ONLINE", "Conectado"),
                            ("OFFLINE", "Desconectado"),
                            ("RECONNECTING", "Reconectando"),
                        ],
                        default="OFFLINE",
                        max_length=20,
                    ),
                ),
                ("connected_at", models.DateTimeField(blank=True, null=True)),
                ("disconnected_at", models.DateTimeField(blank=True, null=True)),
                ("is_chat_muted", models.BooleanField(default=False)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="participants",
                        to="live_sessions.livesession",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="participations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Participante",
                "verbose_name_plural": "Participantes",
                "ordering": ["-points"],
                "unique_together": {("session", "user")},
            },
        ),
    ]
