# Generated by Django 4.2.13 on 2026-05-26 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("live_sessions", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stage",
            name="stage_type",
            field=models.CharField(
                choices=[
                    ("BOARD", "Pizarra"),
                    ("PDF", "PDF"),
                    ("PRESENTATION", "Presentación colaborativa"),
                    ("VIDEO", "Video"),
                    ("QUIZ", "Quiz / Encuesta"),
                    ("CHAT_FOCUS", "Chat enfocado"),
                    ("GAME", "Juego (Ruleta / Timer)"),
                    ("RESOURCE", "Nube de recursos"),
                    ("BREAK", "Descanso"),
                ],
                db_index=True,
                max_length=20,
            ),
        ),
    ]
