# Generated by Django 4.2.13 on 2026-05-12 22:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("live_sessions", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="QuizQuestion",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("text", models.TextField()),
                (
                    "question_type",
                    models.CharField(
                        choices=[
                            ("MULTIPLE_CHOICE", "Opción múltiple"),
                            ("OPEN", "Respuesta abierta"),
                        ],
                        default="MULTIPLE_CHOICE",
                        max_length=20,
                    ),
                ),
                ("options", models.JSONField(default=list)),
                ("correct_answer", models.CharField(blank=True, max_length=1000)),
                ("explanation", models.TextField(blank=True)),
                (
                    "difficulty",
                    models.CharField(
                        choices=[
                            ("EASY", "Fácil"),
                            ("MEDIUM", "Medio"),
                            ("HARD", "Difícil"),
                        ],
                        default="MEDIUM",
                        max_length=10,
                    ),
                ),
                ("duration_seconds", models.PositiveIntegerField(default=30)),
                ("is_launched", models.BooleanField(default=False)),
                ("launched_at", models.DateTimeField(blank=True, null=True)),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
                ("generated_by_ai", models.BooleanField(default=False)),
                ("ai_model_used", models.CharField(blank=True, max_length=100)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quiz_questions",
                        to="live_sessions.livesession",
                    ),
                ),
                (
                    "stage",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="quiz_questions",
                        to="live_sessions.stage",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pregunta de quiz",
                "verbose_name_plural": "Preguntas de quiz",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="Timer",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("label", models.CharField(default="Temporizador", max_length=200)),
                ("duration_seconds", models.PositiveIntegerField()),
                ("end_timestamp_utc", models.DateTimeField()),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("RUNNING", "Corriendo"),
                            ("PAUSED", "Pausado"),
                            ("CANCELLED", "Cancelado"),
                            ("FINISHED", "Finalizado"),
                        ],
                        default="RUNNING",
                        max_length=20,
                    ),
                ),
                ("paused_at", models.DateTimeField(blank=True, null=True)),
                (
                    "remaining_seconds",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="timers",
                        to="live_sessions.livesession",
                    ),
                ),
            ],
            options={
                "verbose_name": "Temporizador",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PointEvent",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("points", models.IntegerField()),
                (
                    "action_label",
                    models.CharField(default="Participación", max_length=200),
                ),
                (
                    "awarded_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="awarded_points",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "participant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="point_events",
                        to="live_sessions.participant",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="point_events",
                        to="live_sessions.livesession",
                    ),
                ),
            ],
            options={
                "verbose_name": "Evento de puntos",
                "verbose_name_plural": "Eventos de puntos",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="QuizResponse",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("answer", models.CharField(max_length=1000)),
                ("is_correct", models.BooleanField(blank=True, null=True)),
                ("answered_at", models.DateTimeField(auto_now_add=True)),
                (
                    "participant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quiz_responses",
                        to="live_sessions.participant",
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="responses",
                        to="gamification.quizquestion",
                    ),
                ),
            ],
            options={
                "verbose_name": "Respuesta de quiz",
                "unique_together": {("question", "participant")},
            },
        ),
    ]
