# Generated by Django 4.2.13 on 2026-05-12 22:20

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AIGenerationLog",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "task_type",
                    models.CharField(
                        choices=[
                            ("QUESTIONS", "Generación de preguntas"),
                            ("SUMMARY", "Resumen de sesión"),
                            ("LIVE_HINT", "Sugerencia en vivo"),
                        ],
                        max_length=20,
                    ),
                ),
                ("input_hash", models.CharField(blank=True, max_length=64)),
                ("output", models.JSONField(blank=True, null=True)),
                ("model_used", models.CharField(blank=True, max_length=100)),
                ("prompt_tokens", models.PositiveIntegerField(default=0)),
                ("completion_tokens", models.PositiveIntegerField(default=0)),
                ("duration_ms", models.PositiveIntegerField(default=0)),
                ("error", models.TextField(blank=True)),
                ("is_success", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Log de generación IA",
                "verbose_name_plural": "Logs de generación IA",
                "ordering": ["-created_at"],
            },
        ),
    ]
