# Generated by Django 4.2.13 on 2026-05-12 22:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("live_sessions", "0001_initial"),
        ("ai_copilot", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="aigenerationlog",
            name="session",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ai_logs",
                to="live_sessions.livesession",
            ),
        ),
    ]
