# Generated by Django 4.2.13 on 2026-05-12 22:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("live_sessions", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Snippet",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=255)),
                (
                    "language",
                    models.CharField(
                        choices=[
                            ("python", "Python"),
                            ("javascript", "JavaScript"),
                            ("typescript", "TypeScript"),
                            ("sql", "SQL"),
                            ("bash", "Bash / Shell"),
                            ("html", "HTML"),
                            ("css", "CSS"),
                            ("json", "JSON"),
                            ("yaml", "YAML"),
                            ("java", "Java"),
                            ("cpp", "C++"),
                            ("csharp", "C#"),
                            ("go", "Go"),
                            ("rust", "Rust"),
                            ("other", "Otro"),
                        ],
                        default="other",
                        max_length=20,
                    ),
                ),
                ("content", models.TextField()),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="snippets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="snippets",
                        to="live_sessions.livesession",
                    ),
                ),
                (
                    "stage",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="snippets",
                        to="live_sessions.stage",
                    ),
                ),
            ],
            options={
                "verbose_name": "Snippet",
                "verbose_name_plural": "Snippets",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Resource",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=500)),
                (
                    "resource_type",
                    models.CharField(
                        choices=[
                            ("PDF", "PDF"),
                            ("IMAGE", "Imagen"),
                            ("ZIP", "ZIP / Comprimido"),
                            ("CODE", "Código fuente"),
                            ("OTHER", "Otro"),
                        ],
                        default="OTHER",
                        max_length=10,
                    ),
                ),
                ("file_key", models.CharField(max_length=1000)),
                ("size_bytes", models.PositiveBigIntegerField(default=0)),
                ("content_type", models.CharField(blank=True, max_length=200)),
                ("presigned_url", models.URLField(blank=True, max_length=2000)),
                ("url_expires_at", models.DateTimeField(blank=True, null=True)),
                ("is_uploaded", models.BooleanField(default=False)),
                ("is_dry_run_temp", models.BooleanField(default=False)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resources",
                        to="live_sessions.livesession",
                    ),
                ),
                (
                    "stage",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="resources",
                        to="live_sessions.stage",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="uploaded_resources",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Recurso",
                "verbose_name_plural": "Recursos",
                "ordering": ["-created_at"],
            },
        ),
    ]
