# Generated by Django 4.2.13 on 2026-05-26 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resources", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="resource",
            name="resource_type",
            field=models.CharField(
                choices=[
                    ("PDF", "PDF"),
                    ("PRESENTATION", "Presentación"),
                    ("IMAGE", "Imagen"),
                    ("ZIP", "ZIP / Comprimido"),
                    ("CODE", "Código fuente"),
                    ("OTHER", "Otro"),
                ],
                default="OTHER",
                max_length=20,
            ),
        ),
    ]
